<script setup lang="ts">
const props = defineProps<{ academyId: number; electionId: number; canManage: boolean; status: string }>()
const { listParties, approveParty, rejectParty, withdrawParty } = useElections()
const parties = ref<any[]>([]); const loading = ref(false); const note = ref('')
const load = async () => { loading.value = true; const response: any = await listParties(props.academyId, props.electionId); parties.value = response?.data || []; loading.value = false }
const approve = async (party: any) => { await approveParty(props.academyId, props.electionId, party.id, party.number || null); await load() }
const reject = async (party: any) => { if (!note.value.trim()) return; await rejectParty(props.academyId, props.electionId, party.id, note.value); note.value = ''; await load() }
const withdraw = async (party: any) => { if (confirm('ยืนยันการถอนตัวของพรรคนี้หรือไม่')) { await withdrawParty(props.academyId, props.electionId, party.id); await load() } }
watch(() => [props.academyId, props.electionId], () => { if (props.academyId) load() }, { immediate: true })
</script>
<template>
  <div class="space-y-4"><div v-if="!parties.length" class="rounded-xl border border-dashed p-8 text-center text-gray-500">ยังไม่มีพรรค</div><div class="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700"><table class="min-w-[760px] w-full text-left text-sm"><thead class="bg-gray-50 dark:bg-gray-700"><tr><th class="p-3">เบอร์</th><th class="p-3">ชื่อพรรค</th><th class="p-3">สมาชิก</th><th class="p-3">สถานะ</th><th class="p-3">การจัดการ</th></tr></thead><tbody><tr v-for="party in parties" :key="party.id" class="border-t dark:border-gray-700"><td class="p-3">{{ party.number ?? 'ว่าง' }}</td><td class="p-3">{{ party.name }}</td><td class="p-3">{{ party.members?.map((member: any) => `${member.user?.name || '-'} (${member.role})`).join(', ') || '-' }}</td><td class="p-3">{{ party.status }}</td><td class="space-y-2 p-3"><div class="flex gap-2"><button :disabled="!canManage || !['nomination', 'campaign'].includes(status) || party.status !== 'pending'" class="min-h-[44px] rounded-lg bg-emerald-600 px-3 text-white disabled:opacity-50" @click="approve(party)">อนุมัติ</button><button :disabled="!canManage || !['nomination', 'campaign'].includes(status) || party.status !== 'pending'" class="min-h-[44px] rounded-lg bg-red-600 px-3 text-white disabled:opacity-50" @click="reject(party)">ปฏิเสธ</button><button :disabled="!canManage || party.status !== 'approved'" class="min-h-[44px] rounded-lg border px-3 disabled:opacity-50" @click="withdraw(party)">ถอนตัว</button></div><input v-if="party.status === 'pending'" v-model="note" class="min-h-[44px] w-full rounded-lg border p-2" placeholder="เหตุผลปฏิเสธ (บังคับ)" /></td></tr></tbody></table></div></div>
</template>
