<?php

namespace Database\Seeders;

use App\Models\TypingWord;
use App\Models\TypingSentence;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypingExpansionSeeder extends Seeder
{
    public function run(): void
    {
        // 1. English Expansion
        $en_words = [
            'beginner' => ['the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'I', 'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take', 'person', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us'],
            'easy' => ['about', 'above', 'across', 'act', 'add', 'afraid', 'after', 'again', 'against', 'age', 'ago', 'agree', 'air', 'all', 'allow', 'almost', 'along', 'already', 'also', 'always', 'am', 'among', 'amount', 'an', 'and', 'anger', 'animal', 'another', 'answer', 'any', 'anyone', 'anything', 'appear', 'apple', 'are', 'area', 'arm', 'army', 'around', 'arrive', 'art', 'as', 'ask', 'at', 'attack', 'aunt', 'autumn', 'away', 'baby', 'back', 'bad', 'bag', 'ball', 'bank', 'base', 'basket', 'bath', 'be', 'bean', 'bear', 'beautiful', 'bed', 'bee', 'beer', 'before', 'begin', 'behind', 'believe', 'bell', 'below', 'beside', 'best', 'better', 'between', 'big', 'bird', 'birth', 'bit', 'bite', 'black', 'bleed', 'block', 'blood', 'blow', 'blue', 'board', 'boat', 'body', 'boil', 'bone', 'book', 'boot', 'born', 'borrow', 'both', 'bottle', 'bottom', 'bowl', 'box', 'boy'],
            'normal' => ['between', 'another', 'through', 'because', 'without', 'against', 'during', 'country', 'problem', 'program', 'government', 'company', 'number', 'system', 'business', 'student', 'information', 'service', 'community', 'experience', 'everything', 'something', 'important', 'political', 'different', 'together', 'university', 'available', 'including', 'themselves', 'technology', 'education', 'environment', 'perspective', 'development', 'opportunity', 'performance', 'management', 'understand', 'individual', 'particular', 'successful', 'additional', 'difference', 'especially', 'knowledge', 'sometimes', 'certainly', 'following', 'beginning', 'financial', 'necessary', 'questions', 'president', 'resources', 'attention', 'condition', 'standard', 'statement', 'investment', 'character', 'collection', 'commercial', 'comparison', 'confidence', 'connection', 'difference', 'discussion', 'efficiency', 'electrical', 'expression', 'generation', 'historical', 'indication', 'investment', 'management', 'membership', 'percentage', 'population', 'production', 'protection', 'reflection', 'resolution', 'scientific', 'structural', 'successful', 'suggestion', 'television', 'transition'],
            'hard' => ['achievement', 'acknowledgment', 'administrative', 'advertisement', 'agricultural', 'alternative', 'ambassador', 'anniversary', 'anticipation', 'arrangement', 'articulation', 'association', 'astronomy', 'authentication', 'background', 'bibliography', 'biodiversity', 'biotechnology', 'calculation', 'celebration', 'characterization', 'circumstance', 'classification', 'collaboration', 'combination', 'communication', 'comparison', 'competition', 'composition', 'concentration', 'conception', 'conclusion', 'conditioning', 'configuration', 'confirmation', 'connection', 'consequence', 'conservation', 'consideration', 'consistency', 'constitution', 'construction', 'consultation', 'consumption', 'contemporary', 'continuation', 'contribution', 'controversial', 'convenience', 'cooperation', 'correlation', 'correspondence', 'crystallization', 'demonstration', 'determination', 'differentiation', 'disappointment', 'discrimination', 'distribution', 'documentation', 'effectiveness', 'establishment', 'evolutionary', 'exaggeration', 'expectations', 'experimental', 'explanation', 'facilitation', 'fluctuation', 'foundation', 'generalization', 'globalization', 'identification', 'illumination', 'illustration', 'imagination', 'implementation', 'improvement', 'independence', 'indication', 'individualism', 'industrialization', 'information', 'infrastructure', 'innovation', 'installation', 'institution', 'instruction', 'integration', 'intelligence', 'interaction', 'interference', 'interpretation', 'intervention', 'introduction', 'investigation', 'justification', 'legislation', 'limitation', 'maintenance', 'manipulation'],
            'expert' => ['anachronistic', 'anthropomorphic', 'autobiographical', 'circumlocution', 'compartmentalization', 'conceptualization', 'counter-intuitive', 'deinstitutionalization', 'disproportionate', 'electrocardiogram', 'epistemological', 'extraterrestrial', 'historiography', 'idiosyncrasy', 'incompatibility', 'inconsequential', 'indistinguishable', 'infrastructure', 'institutionalization', 'intercontinental', 'interdisciplinary', 'interpretation', 'juxtaposition', 'lexicographical', 'magnanimous', 'metamorphosis', 'microprocessor', 'multiculturalism', 'nondiscrimination', 'ornithological', 'paleontology', 'parliamentary', 'pharmaceutical', 'philanthropic', 'philosophical', 'photosynthesis', 'procrastination', 'psychoanalysis', 'questionnaire', 'reconciliation', 'rehabilitation', 'representation', 'revolutionary', 'sustainability', 'synchronization', 'telecommunications', 'thermometer', 'transcendental', 'unbelievable', 'underprivileged', 'unprecedented', 'unprofessional', 'unreliability', 'unsatisfactory', 'utilitarianism', 'ventriloquism', 'vulnerability', 'weatherproofing', 'xenotransplantation', 'yestercentury', 'zoogeographical', 'absenteeism', 'acclimatization', 'accountability', 'alphabetization', 'anonymization', 'bioluminescent', 'characterization', 'commercialization', 'democratization', 'differentiation', 'discontinuation', 'diversification', 'electromagnetic', 'environmentalist', 'experimentation', 'functionalism', 'generalization', 'homogenization', 'hospitalization', 'idealization', 'identification', 'individualism', 'industrialization', 'intellectualism', 'internationalization', 'materialization', 'miniaturization', 'misinterpretation', 'misrepresentation', 'modernization', 'neutralization', 'operationalization', 'organization', 'oversimplification', 'personalization', 'popularization', 'privatization', 'professionalism', 'rationalization', 'reorganization', 'secularization', 'specialization', 'standardization']
        ];

        // 2. Thai Expansion
        $th_words = [
            'beginner' => ['ไป', 'มา', 'กิน', 'นอน', 'รัก', 'ดี', 'ใจ', 'น้ำ', 'ข้าว', 'พ่อ', 'แม่', 'พี่', 'น้อง', 'ดู', 'เล่น', 'เดิน', 'วิ่ง', 'ทำ', 'พูด', 'ฟัง', 'อ่าน', 'เขียน', 'เรียน', 'ครู', 'บ้าน', 'รถ', 'คน', 'เรา', 'เขา', 'เธอ', 'นะ', 'คะ', 'ครับ', 'จะ', 'ได้', 'มี', 'เป้น', 'ไม่', 'ใช่', 'หมู', 'หมา', 'กา', 'ไก่', 'ไข่', 'ปู', 'ปลา', 'กุ้ง', 'หอย', 'เต่า', 'ช้าง', 'ม้า', 'วัว', 'ควาย', 'นก', 'หนู', 'แมว', 'ลิง', 'เสือ', 'สิงห์', 'หมี', 'งู', 'กบ', 'เขียด', 'คางคก', 'อึ่งอ่าง', 'จิ้งจก', 'ตุ๊กแก', 'แมลง', 'มด', 'ผึ้ง', 'ต่อ', 'แตน', 'ยุง', 'แมลงวัน', 'แมลงสาบ', 'เห็บ', 'หมัด', 'ไร', 'ฝุ่น', 'ลม', 'ฝน', 'แดด', 'เมฆ', 'ฟ้า', 'ดิน', 'ทราย', 'หิน', 'ไฟ', 'เย็น', 'ร้อน', 'หนาว', 'เปียก', 'แห้ง', 'สูง', 'ต่ำ', 'ยาว', 'สั้น', 'ใหญ่', 'เล็ก', 'อ้วน', 'ผอม', 'ดำ', 'ขาว', 'แดง', 'เขียว', 'ฟ้า', 'เหลือง'],
            'easy' => ['นักเรียน', 'อาจารย์', 'โรงเรียน', 'มหาลัย', 'ท้องฟ้า', 'ทะเล', 'ภูเขา', 'ดอกไม้', 'คอมพิวเตอร์', 'อินเทอร์เน็ต', 'โทรศัพท์', 'หนังสือ', 'สมุด', 'ปากกา', 'ดินสอ', 'ยางลบ', 'ไม้บรรทัด', 'กระเป๋า', 'เสื้อผ้า', 'กางเกง', 'กระโปรง', 'รองเท้า', 'ถุงเท้า', 'หมวก', 'แว่นตา', 'นาฬิกา', 'แหวน', 'สร้อย', 'ตุ้มหู', 'กำไล', 'เข็มขัด', 'ร่ม', 'ตะกร้า', 'ช้อน', 'ส้อม', 'ตะเกียบ', 'จาน', 'ชาม', 'แก้ว', 'ขวด', 'หม้อ', 'กระทะ', 'เตา', 'ตู้เย็น', 'พัดลม', 'แอร์', 'ทีวี', 'วิทยุ', 'ลำโพง', 'ไมค์', 'หูฟัง', 'เมาส์', 'คีย์บอร์ด', 'จอ', 'เคส', 'ปลั๊ก', 'สายไฟ', 'ไฟฉาย', 'ถ่าน', 'แบต', 'ยา', 'หมอ', 'พยาบาล', 'โรงบาล', 'ตำรวจ', 'ทหาร', 'วัด', 'ตลาด', 'ห้าง', 'เซเว่น', 'ข้าวผัด', 'กะเพรา', 'ต้มยำ', 'ส้มตำ', 'ลาบ', 'น้ำตก', 'กาแฟ', 'ชา', 'นม', 'น้ำส้ม', 'น้ำแดง', 'ไอติม', 'ขนม', 'เค้ก', 'คุ้กกี้', 'ขนมปัง', 'ผลไม้', 'สับปะรด', 'แตงโม', 'มะละกอ', 'ทุเรียน', 'มังคุด', 'เงาะ', 'ลำไย', 'ลิ้นจี่', 'ส้ม', 'กล้วย', 'มะม่วง', 'องุ่น', 'มะพร้าว'],
            'normal' => ['การศึกษา', 'ความมั่นคง', 'ความสุข', 'เทคโนโลยี', 'การทำงาน', 'ประวัติศาสตร์', 'ธรรมชาติ', 'สิ่งแวดล้อม', 'เศรษฐกิจ', 'การเมือง', 'วัฒนธรรม', 'วิทยาศาสตร์', 'คณิตศาสตร์', 'ภาษาไทย', 'ภาษาอังกฤษ', 'ภูมิศาสตร์', 'ดาราศาสตร์', 'ศิลปะ', 'ดนตรี', 'กีฬา', 'สุขภาพ', 'อาหาร', 'ท่องเที่ยว', 'ครอบครัว', 'มิตรภาพ', 'ความรัก', 'ความฝัน', 'เป้าหมาย', 'ความสำเร็จ', 'ความพยายาม', 'ความอดทน', 'ความซื่อสัตย์', 'ความกตัญญู', 'ความเมตตา', 'ความเสียสละ', 'จิตอาสา', 'ประชาธิปไตย', 'สิทธิมนุษยชน', 'ความเท่าเทียม', 'ความยุติธรรม', 'กฎหมาย', 'สันติภาพ', 'ความสามัคคี', 'การพัฒนา', 'นวัตกรรม', 'ความคิดสร้างสรรค์', 'วิสัยทัศน์', 'กลยุทธ์', 'การบริหาร', 'ภาวะผู้นำ', 'ทีมเวิร์ค', 'การสื่อสาร', 'การเจรจา', 'การแก้ปัญหา', 'การตัดสินใจ', 'ความรับผิดชอบ', 'ความน่าเชื่อถือ', 'คุณภาพ', 'มาตรฐาน', 'ประสิทธิภาพ', 'ประสิทธิผล', 'ความยั่งยืน', 'การอนุรักษ์', 'ภาวะโลกร้อน', 'พลังงานสะอาด', 'เศรษฐกิจพอเพียง', 'ดิจิทัล', 'ออนไลน์', 'โซเชียล', 'ข้อมูล', 'ความรู้', 'ประสบการณ์', 'ทักษะ', 'พรสวรรค์', 'โอกาส', 'อุปสรรค', 'ความล้มเหลว', 'บทเรียน', 'แรงบันดาลใจ', 'ทัศนคติ', 'ความคิด', 'ความรู้สึก', 'จินตนาการ', 'แรงจูงใจ', 'สมาธิ', 'สติ', 'ปัญญา', 'วิจารณญาณ', 'จริยธรรม', 'คุณธรรม', 'มโนธรรม', 'อุดมการณ์', 'ศรัทธา', 'ความเชื่อ', 'ความหวัง', 'ความภูมิใจ', 'ความยินดี'],
            'hard' => ['อารยธรรม', 'สถาปัตยกรรม', 'จิตรกรรม', 'ประติมากรรม', 'วรรณกรรม', 'โบราณคดี', 'มานุษยวิทยา', 'สังคมวิทยา', 'จิตวิทยา', 'ปรัชญา', 'ศาสนศาสตร์', 'รัฐศาสตร์', 'นิติศาสตร์', 'นิเทศศาสตร์', 'ครุศาสตร์', 'แพทยศาสตร์', 'เภสัชศาสตร์', 'พยาบาลศาสตร์', 'ทันตแพทยศาสตร์', 'สัตวแพทยศาสตร์', 'วิศวกรรมศาสตร์', 'สถาปัตยกรรมศาสตร์', 'วิทยาศาสตร์ประยุกต์', 'เทคโนโลยีสารสนเทศ', 'นาโนเทคโนโลยี', 'เทคโนโลยีชีวภาพ', 'วิศวกรรมพันธุกรรม', 'ปัญญาประดิษฐ์', 'วิทยาการข้อมูล', 'ความปลอดภัยทางไซเบอร์', 'บล็อกเชน', 'สกุลเงินดิจิทัล', 'การประมวลผลแบบคลาวด์', 'อินเทอร์เน็ตของสรรพสิ่ง', 'ความเป็นจริงเสมือน', 'ความเป็นจริงเสริม', 'การสำรวจอวกาศ', 'ฟิสิกส์ควอนตัม', 'ทฤษฎีสัมพัทธภาพ', 'วิวัฒนาการ', 'พันธุศาสตร์', 'อณูชีววิทยา', 'นิเวศวิทยา', 'สมุทรศาสตร์', 'อุตุนิยมวิทยา', 'ธรณีวิทยา', 'บรรพชีวินวิทยา', 'ดาราศาสตร์ฟิสิกส์', 'จักรวาลวิทยา', 'คณิตศาสตร์ประกันภัย', 'สถิติประยุกต์', 'วิจัยปฏิบัติการ', 'การจำลองสถานการณ์', 'การเพิ่มประสิทธิภาพ', 'การจัดการเชิงกลยุทธ์', 'การจัดการห่วงโซ่อุปทาน', 'โลจิสติกส์', 'พาณิชย์อิเล็กทรอนิกส์', 'การตลาดดิจิทัล', 'พฤติกรรมผู้บริโภค', 'การวิเคราะห์การตลาด', 'การสื่อสารแบรนด์', 'ประชาสัมพันธ์', 'สื่อสารมวลชน', 'วารสารศาสตร์', 'การผลิตภาพยนตร์', 'แอนิเมชัน', 'มัลติมีเดีย', 'การออกแบบกราฟิก', 'การออกแบบผลิตภัณฑ์', 'การออกแบบแฟชั่น', 'การออกแบบภายใน', 'ภูมิสถาปัตยกรรม', 'การวางผังเมือง', 'การจัดการสิ่งแวดล้อม', 'การประเมินผลกระทบ', 'กฎหมายระหว่างประเทศ', 'ความสัมพันธ์ระหว่างประเทศ', 'องค์การระหว่างประเทศ', 'โลกาภิวัตน์', 'ภูมิรัฐศาสตร์', 'เศรษฐศาสตร์มหภาค', 'เศรษฐศาสตร์จุลภาค', 'นโยบายการเงิน', 'นโยบายการคลัง', 'ตลาดทุน', 'ตลาดเงิน', 'ตราสารหนี้', 'ตราสารทุน', 'อนุพันธ์ทางการเงิน', 'การบริหารความเสี่ยง', 'บรรษัทภิบาล', 'ความรับผิดชอบต่อสังคม', 'การพัฒนาที่ยั่งยืน'],
            'expert' => ['พจนาศรม', 'วิมรรศนา', 'สุนทรียศาสตร์', 'ปฏิมาวิทยา', 'อรรถปริวรรต', 'วาทศิลป์', 'วาทศาสตร์', 'ตรรกศาสตร์', 'ภววิทยา', 'ญาณวิทยา', 'คุณวิทยา', 'สัญวิทยา', 'นิรุกติศาสตร์', 'อักขรวิทยา', 'สังคีตศิลป์', 'นาฏศิลป์', 'คีตลักษณ์', 'ดุริยางคศิลป์', 'จริยศาสตร์', 'สุนทรียทัศน์', 'รังสรรค์', 'วิจิตรศิลป์', 'มัณฑนศิลป์', 'ประยุกต์ศิลป์', 'ทัศนศิลป์', 'วิจารณญาณ', 'กัลยาณมิตร', 'ไตรสิกขา', 'อิทธิบาท', 'พรหมวิหาร', 'สังคหวัตถุ', 'ฆราวาสธรรม', 'สัปปุริสธรรม', 'มงคลชีวิต', 'ทศพิธราชธรรม', 'จักรวรรดิวัตร', 'อคติ', 'วิมุตติ', 'สัมมาทิฐิ', 'มรรคผล', 'นิพพาน', 'อนัตตา', 'ไตรลักษณ์', 'ปฏิจจสมุปบาท', 'อริยสัจ', 'สติปัฏฐาน', 'วิปัสสนา', 'สมถะ', 'ฌาน', 'ญาณ', 'วิมุตติญาณทัศนะ', 'ธรรมนูญ', 'สภาร่างรัฐธรรมนูญ', 'นิติบัญญัติ', 'บริหาร', 'ตุลาการ', 'อธิปไตย', 'สิทธิเสรีภาพ', 'เสมอภาค', 'ภราดรภาพ', 'ความตกลงระหว่างประเทศ', 'สนธิสัญญา', 'พิธีสาร', 'สัตยาบัน', 'ภาคยานุวัติ', 'เอกสิทธิ์ทางการทูต', 'ความคุ้มกันทางการทูต', 'การส่งผู้ร้ายข้ามแดน', 'การลี้ภัย', 'ความมั่นคงของมนุษย์', 'ความปลอดภัยของมนุษย์', 'ทุนมนุษย์', 'ทรัพยากรมนุษย์', 'การพัฒนาทรัพยากรมนุษย์', 'องค์การมหาชน', 'วิสาหกิจชุมชน', 'สหกรณ์', 'ธรรมาภิบาล', 'โปร่งใส', 'ตรวจสอบได้', 'ประเมินผล', 'สัมฤทธิผล', 'บูรณาการ', 'ประสานงาน', 'สัมพันธภาพ', 'เอกลักษณ์', 'อัตลักษณ์', 'บริบท', 'พลวัต', 'วิวัฒนาการ', 'อารยธรรม', 'มรดกโลก', 'ภูมิปัญญาท้องถิ่น', 'ซอฟต์พาวเวอร์', 'เศรษฐกิจสร้างสรรค์', 'นวัตกรรมทางสังคม', 'กิจการเพื่อสังคม', 'การลงทุนที่รับผิดชอบ', 'สิ่งแวดล้อม สังคม และธรรมาภิบาล']
        ];

        // 3. Arabic Expansion (Basic set)
        $ar_words = [
            'beginner' => ['أنا', 'أنت', 'هو', 'هي', 'نحن', 'في', 'من', 'إلى', 'على', 'مع', 'هذا', 'هذه', 'كان', 'قال', 'ذهب', 'جاء', 'رأى', 'أكل', 'شرب', 'نام', 'حب', 'بيت', 'ولد', 'بنت', 'أب', 'أم', 'أخ', 'أخت', 'مدرسة', 'كتاب', 'قلم', 'ماء', 'خبز', 'شاي', 'قهوة', 'شمس', 'قمر', 'سماء', 'أرض', 'بحر', 'نهر', 'جبل', 'شجرة', 'وردة', 'كلب', 'قطة', 'أسد', 'فيل', 'جمل', 'خيل'],
            'easy' => ['طالب', 'معلم', 'طبيب', 'مهندس', 'شرطي', 'جندي', 'مستشفى', 'حديقة', 'سيارة', 'طائرة', 'سفينة', 'دراجة', 'ساعة', 'نظارة', 'حقيبة', 'كرسي', 'طاولة', 'نافذة', 'باب', 'مفتاح', 'هاتف', 'حاسوب', 'تلفاز', 'راديو', 'شارع', 'مدينة', 'قرية', 'سوق', 'مسجد', 'صلاة', 'يوم', 'أسبوع', 'شهر', 'سنة', 'وقت', 'ساعة', 'دقيقة', 'ثانية', 'صباح', 'مساء', 'ليل', 'نهار', 'شتاء', 'صيف', 'ربيع', 'خريف', 'أبيض', 'أسود', 'أحمر', 'أخضر', 'أزرق', 'أصفر'],
            'normal' => ['تعليم', 'صحة', 'عمل', 'سفر', 'رياضة', 'موسيقى', 'فن', 'ثقافة', 'تاريخ', 'جغرافيا', 'علوم', 'رياضيات', 'لغة', 'أدب', 'شعر', 'قصة', 'رواية', 'صحافة', 'إعلام', 'سياسة', 'اقتصاد', 'تجارة', 'سياحة', 'تنمية', 'تكنولوجيا', 'بيئة', 'طبيعة', 'فضاء', 'كواكب', 'نجوم', 'مجرة', 'حقيقة', 'خيال', 'أمل', 'سلام', 'حرية', 'عدالة', 'مساواة', 'حقوق', 'واجبات', 'قانون', 'دستور', 'ديمقراطية', 'وطن', 'أمة', 'شعب', 'إنسان', 'مجتمع', 'عائلة', 'صداقة'],
            'hard' => ['حضارة', 'فلسفة', 'منطق', 'أخلاق', 'جمال', 'معرفة', 'وعي', 'إدراك', 'تفكير', 'إبداع', 'ابتكار', 'ذكاء', 'تجربة', 'برهان', 'نظرية', 'منهج', 'تحليل', 'تركيب', 'نقد', 'تأويل', 'رمز', 'أسطورة', 'تراث', 'حداثة', 'نهضة', 'ثورة', 'إصلاح', 'تغيير', 'تطور', 'تقدم', 'ازدهار', 'استقرار', 'أمن', 'سيادة', 'استقلال', 'تحرر', 'كرامة', 'تضامن', 'تعاون', 'تكامل', 'حوار', 'تفاهم', 'تسامح', 'تعايش', 'تنوع', 'انفتاح', 'عولمة', 'هوية', 'انتماء', 'تضحية'],
            'expert' => ['استراتيجية', 'بيروقراطية', 'ديكتاتورية', 'أيديولوجيا', 'رأسمالية', 'اشتراكية', 'ليبرالية', 'علمانية', 'راديكالية', 'براغماتية', 'لوجستية', 'بروتوكول', 'دبلوماسية', 'اتفاقية', 'معاهدة', 'ميثاق', 'منظمة', 'مؤسسة', 'هيئة', 'مجلس', 'لجنة', 'محكمة', 'نيابة', 'سلطة', 'إدارة', 'حكومة', 'برلمان', 'انتخابات', 'استفتاء', 'شرعية', 'مشروعية', 'سيادة', 'حصانة', 'امتياز', 'التزام', 'مسؤولية', 'شفافية', 'نزاهة', 'كفاءة', 'فعالية', 'إنتاجية', 'جودة', 'تميز', 'استدامة', 'مرونة', 'تفاعل', 'تواصل', 'انسجام', 'توازن', 'ريادة']
        ];

        $insert_words = [];
        $now = now();

        foreach (['en', 'th', 'ar'] as $lang) {
            $data = ($lang === 'en') ? $en_words : (($lang === 'th') ? $th_words : $ar_words);
            foreach ($data as $diff => $words) {
                foreach ($words as $word) {
                    $insert_words[] = [
                        'language' => $lang,
                        'difficulty' => $diff,
                        'category' => 'general',
                        'text' => $word,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }
            }
        }

        // Use chunk to avoid large insert error
        foreach (array_chunk($insert_words, 100) as $chunk) {
            DB::table('typing_words')->insert($chunk);
        }

        // 4. Sentences Expansion
        $sentences = [
            // EN
            ['language' => 'en', 'difficulty' => 'easy', 'text' => 'The quick brown fox jumps over the lazy dog.', 'word_count' => 9],
            ['language' => 'en', 'difficulty' => 'easy', 'text' => 'She sells seashells by the seashore.', 'word_count' => 7],
            ['language' => 'en', 'difficulty' => 'easy', 'text' => 'Life is what happens when you are busy making other plans.', 'word_count' => 11],
            ['language' => 'en', 'difficulty' => 'normal', 'text' => 'The only way to do great work is to love what you do.', 'word_count' => 12],
            ['language' => 'en', 'difficulty' => 'normal', 'text' => 'In the middle of every difficulty lies opportunity.', 'word_count' => 8],
            ['language' => 'en', 'difficulty' => 'hard', 'text' => 'Success is not final, failure is not fatal: it is the courage to continue that counts.', 'word_count' => 16],
            ['language' => 'en', 'difficulty' => 'hard', 'text' => 'The future belongs to those who believe in the beauty of their dreams.', 'word_count' => 13],
            ['language' => 'en', 'difficulty' => 'expert', 'text' => 'Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.', 'word_count' => 20],
            
            // TH
            ['language' => 'th', 'difficulty' => 'easy', 'text' => 'การเรียนรู้ไม่มีวันสิ้นสุด และความพยายามอยู่ที่ไหนความสำเร็จอยู่ที่นั่น', 'word_count' => 10],
            ['language' => 'th', 'difficulty' => 'easy', 'text' => 'วันนี้เป็นวันที่ดี และฉันจะทำให้ดีที่สุดในทุกสิ่งที่ทำ', 'word_count' => 11],
            ['language' => 'th', 'difficulty' => 'normal', 'text' => 'การศึกษาคืออาวุธที่ทรงพลังที่สุดที่คุณสามารถใช้เพื่อเปลี่ยนแปลงโลกใบนี้', 'word_count' => 10],
            ['language' => 'th', 'difficulty' => 'normal', 'text' => 'ความสำเร็จไม่ได้ขึ้นอยู่กับสิ่งที่เรามี แต่ขึ้นอยู่กับสิ่งที่เราเป็นและสิ่งที่เราทำ', 'word_count' => 14],
            ['language' => 'th', 'difficulty' => 'hard', 'text' => 'อุปสรรคคือสิ่งที่น่ากลัวที่คุณจะมองเห็นได้ก็ต่อเมื่อคุณละสายตาไปจากเป้าหมายของคุณ', 'word_count' => 13],
            ['language' => 'th', 'difficulty' => 'hard', 'text' => 'จงใช้ชีวิตราวกับว่าคุณจะตายในวันพรุ่งนี้ และจงเรียนรู้ราวกับว่าคุณจะมีชีวิตอยู่ตลอดไป', 'word_count' => 16],
            ['language' => 'th', 'difficulty' => 'expert', 'text' => 'ในโลกที่เต็มไปด้วยความเปลี่ยนแปลง สิ่งเดียวที่แน่นอนที่สุดคือความไม่แน่นอน ดังนั้นเราจึงควรมีสติอยู่เสมอ', 'word_count' => 17],
            
            // AR
            ['language' => 'ar', 'difficulty' => 'easy', 'text' => 'العلم نور والجهل ظلام، فكن دائماً باحثاً عن المعرفة.', 'word_count' => 9],
            ['language' => 'ar', 'difficulty' => 'normal', 'text' => 'من جد وجد ومن زرع حصد، فاجتهد في عملك تصل إلى مبتغاك.', 'word_count' => 12],
            ['language' => 'ar', 'difficulty' => 'hard', 'text' => 'الوقت كالسيف إن لم تقطعه قطعك، فاستثمر وقتك فيما ينفعك وينفع مجتمعك.', 'word_count' => 14],
        ];

        foreach ($sentences as $sentence) {
            TypingSentence::create($sentence);
        }
    }
}
