<script setup lang="ts">
const props = defineProps<{ academyId: number; scopeType: 'department' | 'classroom'; scopeId: number }>()
const api = useApi(); const active = ref<'tasks' | 'files'>('tasks'); const tasks = ref<any[]>([]); const files = ref<any[]>([]); const title = ref(''); const isLoading = ref(false)
const query = { scope_type: props.scopeType, scope_id: props.scopeId }
const load = async () => { isLoading.value = true; try { const [a, b]: any = await Promise.all([api.get(`/api/academies/${props.academyId}/scope/tasks`, { query }), api.get(`/api/academies/${props.academyId}/scope/files`, { query })]); tasks.value = a.data || []; files.value = b.data || [] } finally { isLoading.value = false } }
const createTask = async () => { if (!title.value.trim()) return; await api.post(`/api/academies/${props.academyId}/scope/tasks`, { ...query, title: title.value.trim() }); title.value = ''; await load() }
const upload = async (event: Event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const body = new FormData(); body.append('file', file); body.append('scope_type', props.scopeType); body.append('scope_id', String(props.scopeId)); await api.post(`/api/academies/${props.academyId}/scope/files`, body); await load() }
onMounted(load)
</script>
<template><section class="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div class="flex gap-2 border-b border-gray-100 pb-3 dark:border-gray-700"><button v-for="item in [{key:'tasks',label:'งาน'},{key:'files',label:'เอกสาร'}]" :key="item.key" class="min-h-[44px] sm:min-h-0 rounded-lg px-3 py-2 text-sm font-medium" :class="active === item.key ? 'bg-primary-50 text-primary-600' : 'text-gray-500'" @click="active = item.key as any">{{ item.label }}</button></div><div v-if="active === 'tasks'" class="pt-4"><div class="flex gap-2"><input v-model="title" class="min-w-0 flex-1 rounded-xl border-gray-200 text-sm dark:border-gray-600 dark:bg-gray-700" placeholder="สร้างงานภายในพื้นที่" @keyup.enter="createTask" /><button class="min-h-[44px] sm:min-h-0 rounded-xl bg-primary-600 px-4 py-2 text-sm font-semibold text-white" @click="createTask">เพิ่ม</button></div><div v-if="isLoading" class="py-8 text-center text-gray-500">กำลังโหลด...</div><div v-else-if="!tasks.length" class="py-8 text-center text-gray-500">ยังไม่มีงาน</div><div v-else class="mt-4 divide-y divide-gray-100 dark:divide-gray-700"><div v-for="task in tasks" :key="task.id" class="flex items-center justify-between py-3"><span class="text-sm text-gray-800 dark:text-gray-200">{{ task.title }}</span><span class="text-xs text-gray-500">{{ task.status }}</span></div></div></div><div v-else class="pt-4"><label class="inline-flex cursor-pointer rounded-xl border border-dashed border-gray-300 px-4 py-3 text-sm text-gray-600 dark:border-gray-600 dark:text-gray-300">อัปโหลดเอกสาร<input type="file" class="hidden" @change="upload" /></label><div v-if="!files.length" class="py-8 text-center text-gray-500">ยังไม่มีเอกสาร</div><div v-else class="mt-4 divide-y divide-gray-100 dark:divide-gray-700"><div v-for="file in files" :key="file.id" class="py-3 text-sm text-gray-800 dark:text-gray-200">{{ file.name }}</div></div></div></section></template>
