import { computed, ref, unref, type ComputedRef } from 'vue'

export interface AcademyDonationClaimable { id: number; donor_display_name: string; donor_avatar?: string | null; donor_personal_code?: string | null; purpose?: string | null; points_amount: number; remaining_points: number; created_at: string; my_claims_today: number; claim_amount_preview: number; claimer_reward_preview: number }
export interface AcademyClaimPagination { current_page: number; last_page: number; per_page: number; total: number; has_more: boolean }
export interface AcademyClaimResponse { ok: true; claim: Record<string, unknown>; wallet: { pp: number; delta: number } }
export class AcademyClaimError extends Error { code: string | number; status?: number; constructor(code: string | number, status?: number) { super(String(code)); this.name = 'AcademyClaimError'; this.code = code; this.status = status } }

export function useAcademyClaimable(academyId: ComputedRef<number | null> | number) {
  const api = useApi(); const id = computed(() => unref(academyId)); const items = ref<AcademyDonationClaimable[]>([]); const pagination = ref<AcademyClaimPagination>({ current_page: 0, last_page: 1, per_page: 12, total: 0, has_more: true }); const meta = ref({ my_claims_today_all_tiers: 0, cap_reached: false }); const loading = ref(false); const error = ref<unknown>(null)
  const fetchClaimable = async (append = false) => { if (!id.value || loading.value || (append && !pagination.value.has_more)) return null; loading.value = true; error.value = null; try { const page = append ? pagination.value.current_page + 1 : 1; const result = await api.get<{ donations: AcademyDonationClaimable[]; pagination?: AcademyClaimPagination; my_claims_today_all_tiers: number; cap_reached: boolean }>(`/api/academies/${id.value}/donations/claimable?page=${page}&per_page=12`); items.value = append ? [...items.value, ...(result.donations ?? [])] : (result.donations ?? []); pagination.value = result.pagination ?? { current_page: page, last_page: page, per_page: 12, total: items.value.length, has_more: false }; meta.value = { my_claims_today_all_tiers: result.my_claims_today_all_tiers ?? 0, cap_reached: result.cap_reached ?? false }; return result } catch (err) { error.value = err; throw err } finally { loading.value = false } }
  const claimFromDonation = async (donationId: number) => { if (!id.value) throw new AcademyClaimError('invalid_academy'); loading.value = true; error.value = null; try { const result = await api.post<AcademyClaimResponse>(`/api/academies/${id.value}/donations/${donationId}/claim`, {}); await fetchClaimable(); return result } catch (err: any) { const status = err?.status ?? err?.statusCode; const data = err?.data ?? err?.response?._data; const typed = err instanceof AcademyClaimError ? err : new AcademyClaimError(data?.code ?? 'claim_failed', status); error.value = typed; throw typed } finally { loading.value = false } }
  return { items, pagination, meta, loading, error, fetchClaimable, claimFromDonation }
}
