import { computed, ref, unref, type ComputedRef } from 'vue'

export interface CourseDonationClaimable { id: number; donor_display_name: string; donor_avatar?: string | null; donor_personal_code?: string | null; purpose?: string | null; points_amount: number; remaining_points: number; created_at: string; my_claims_today: number; claim_amount_preview: number; claimer_reward_preview: number }
export interface CourseClaimHistoryItem { id: number; claimer_name: string | null; claimer_avatar?: string | null; claimer_personal_code?: string | null; donor_display_name: string; amount_claimer: number; amount_course: number; claimed_at: string; is_mine: boolean }
export interface CourseClaimPagination { current_page: number; last_page: number; per_page: number; total: number; has_more: boolean }
export interface CourseClaimResponse { ok: true; claim: Record<string, unknown>; wallet: { pp: number; delta: number } }
export class CourseClaimError extends Error { code: string | number; status?: number; constructor(code: string | number, status?: number) { super(String(code)); this.name = 'CourseClaimError'; this.code = code; this.status = status } }

export function useCourseClaimable(courseId: ComputedRef<number | null> | number) {
  const api = useApi(); const id = computed(() => unref(courseId)); const items = ref<CourseDonationClaimable[]>([]); const pagination = ref<CourseClaimPagination>({ current_page: 0, last_page: 1, per_page: 12, total: 0, has_more: true }); const meta = ref({ my_claims_today_all_tiers: 0, cap_reached: false, pool_total_remaining: 0 }); const loading = ref(false); const error = ref<unknown>(null); const claims = ref<CourseClaimHistoryItem[]>([]); const claimsPagination = ref<CourseClaimPagination>({ current_page: 0, last_page: 1, per_page: 15, total: 0, has_more: false }); const claimsSummary = ref({ total_claims: 0, my_claims_count: 0, my_points_total: 0 }); const claimsLoading = ref(false); const claimsError = ref<unknown>(null)
  const fetchClaimable = async (append = false) => { if (!id.value || loading.value || (append && !pagination.value.has_more)) return null; loading.value = true; error.value = null; try { const page = append ? pagination.value.current_page + 1 : 1; const result = await api.get<{ donations: CourseDonationClaimable[]; pagination?: CourseClaimPagination; my_claims_today_all_tiers: number; cap_reached: boolean; pool_total_remaining?: number }>(`/api/courses/${id.value}/donations/claimable?page=${page}&per_page=12`); items.value = append ? [...items.value, ...(result.donations ?? [])] : (result.donations ?? []); pagination.value = result.pagination ?? { current_page: page, last_page: page, per_page: 12, total: items.value.length, has_more: false }; meta.value = { my_claims_today_all_tiers: result.my_claims_today_all_tiers ?? 0, cap_reached: result.cap_reached ?? false, pool_total_remaining: result.pool_total_remaining ?? 0 }; return result } catch (err) { error.value = err; throw err } finally { loading.value = false } }
  const claimFromDonation = async (donationId: number) => { if (!id.value) throw new CourseClaimError('invalid_course'); loading.value = true; error.value = null; try { const result = await api.post<CourseClaimResponse>(`/api/courses/${id.value}/donations/${donationId}/claim`, {}); await fetchClaimable(); return result } catch (err: any) { const status = err?.status ?? err?.statusCode; const data = err?.data ?? err?.response?._data; const typed = err instanceof CourseClaimError ? err : new CourseClaimError(data?.code ?? 'claim_failed', status); error.value = typed; throw typed } finally { loading.value = false } }
  const fetchClaims = async (append = false) => { if (!id.value || claimsLoading.value || (append && !claimsPagination.value.has_more)) return null; claimsLoading.value = true; claimsError.value = null; try { const page = append ? claimsPagination.value.current_page + 1 : 1; const result = await api.get<{ claims?: CourseClaimHistoryItem[]; pagination?: CourseClaimPagination; summary?: Partial<typeof claimsSummary.value> }>(`/api/courses/${id.value}/donations/claims?page=${page}&per_page=15`); claims.value = append ? [...claims.value, ...(result.claims ?? [])] : (result.claims ?? []); claimsPagination.value = result.pagination ?? { current_page: page, last_page: page, per_page: 15, total: claims.value.length, has_more: false }; claimsSummary.value = { total_claims: result.summary?.total_claims ?? 0, my_claims_count: result.summary?.my_claims_count ?? 0, my_points_total: result.summary?.my_points_total ?? 0 }; return result } catch (err) { claimsError.value = err; claims.value = []; claimsPagination.value = { ...claimsPagination.value, has_more: false }; return null } finally { claimsLoading.value = false } }
  return { items, pagination, meta, loading, error, claims, claimsPagination, claimsSummary, claimsLoading, claimsError, fetchClaimable, claimFromDonation, fetchClaims }
}
