<script setup lang="ts">
import Dialog from 'primevue/dialog'
import { useCourseDonations, type CourseDonation } from '~/composables/useCourseDonations'
const props = defineProps<{ visible: boolean; courseId: number; courseName: string; courseOwnerId: number; balance?: number }>()
const emit = defineEmits<{ 'update:visible': [boolean]; donated: [CourseDonation] }>()
const { sendPointDonation, sendCashDonation } = useCourseDonations()
const step = ref(1); const type = ref<'point'|'cash'>('point'); const points = ref(1); const cash = ref<number | null>(null)
const purpose = ref(''); const anonymous = ref(false); const displayName = ref(''); const paymentMethod = ref('bank_transfer'); const reference = ref(''); const slip = ref<File | null>(null)
const loading = ref(false); const error = ref(''); const fieldErrors = ref<Record<string,string[]>>({}); const result = ref<CourseDonation | null>(null)
const close = () => emit('update:visible', false)
const chooseFile = (event: Event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (file && file.size <= 5 * 1024 * 1024) slip.value = file; else error.value = 'Slip must be an image or PDF up to 5MB.' }
const submit = async () => { loading.value = true; error.value = ''; fieldErrors.value = {}; try { let response: any; if (type.value === 'point') response = await sendPointDonation(props.courseId, { points_amount: points.value, purpose: purpose.value || undefined, anonymous: anonymous.value, donor_display_name: displayName.value || undefined }); else { const form = new FormData(); form.append('cash_amount', String(cash.value || '')); form.append('slip', slip.value as File); form.append('payment_method', paymentMethod.value); if (reference.value) form.append('payment_reference', reference.value); if (purpose.value) form.append('purpose', purpose.value); form.append('anonymous', String(anonymous.value)); if (displayName.value) form.append('donor_display_name', displayName.value); response = await sendCashDonation(props.courseId, form) } result.value = response.data || response; step.value = 5; emit('donated', result.value) } catch (e: any) { if (e.status === 409) { result.value = e.data?.data || e.data?.donation; step.value = 5; if (result.value) emit('donated', result.value) } else if (e.status === 422) fieldErrors.value = e.data?.errors || {}; else error.value = e.data?.message || e.message || 'Unable to submit donation.' } finally { loading.value = false } }
watch(() => props.visible, value => { if (value) { step.value = 1; result.value = null; error.value = ''; fieldErrors.value = {} } })
</script>
<template><Dialog :visible="visible" modal :header="'Support ' + courseName" class="w-full max-w-lg" @update:visible="emit('update:visible', $event)">
  <div class="mb-5 flex items-center gap-2 text-xs text-slate-500"><span v-for="n in 5" :key="n" :class="['h-2 flex-1 rounded-full', n <= step ? 'bg-primary-600' : 'bg-slate-200']" /></div>
  <div v-if="step === 1" class="space-y-3"><h3 class="text-lg font-bold">Choose support type</h3><button v-for="item in [{v:'point',t:'Support with Points'},{v:'cash',t:'Cash donation'}]" :key="item.v" class="w-full rounded-xl border p-4 text-left" :class="type === item.v ? 'border-primary-500 bg-primary-50' : ''" @click="type = item.v as any">{{ item.t }}</button><button class="w-full rounded-xl bg-primary-600 p-3 text-white" @click="step = 2">Next</button></div>
  <div v-else-if="step === 2" class="space-y-4"><h3 class="text-lg font-bold">Amount</h3><label v-if="type === 'point'" class="block">Points<input v-model.number="points" type="number" min="1" step="1" class="mt-1 w-full rounded-lg border p-2" /><small>Current balance: {{ balance ?? '—' }} points</small><p class="mt-2 text-sm">You will support {{ courseName }} with {{ points }} points.</p></label><template v-else><label>Amount<input v-model.number="cash" type="number" min="1" step="0.01" class="mt-1 w-full rounded-lg border p-2" /></label><label>Slip<input type="file" accept="image/*,.pdf,application/pdf" class="mt-1 w-full" @change="chooseFile" /></label><label>Payment method<select v-model="paymentMethod" class="mt-1 w-full rounded-lg border p-2"><option value="bank_transfer">Bank transfer</option><option value="promptpay">PromptPay</option></select></label><label>Payment reference<input v-model="reference" class="mt-1 w-full rounded-lg border p-2" /></label></template><button class="w-full rounded-xl bg-primary-600 p-3 text-white" @click="step = 3">Next</button></div>
  <div v-else-if="step === 3" class="space-y-4"><label>Purpose<textarea v-model="purpose" class="mt-1 w-full rounded-lg border p-2" /></label><label class="flex items-center gap-2"><input v-model="anonymous" type="checkbox" /> Anonymous <span title="ชื่อจะไม่ถูกแสดงต่อสาธารณะ แต่ระบบยังบันทึกไว้">ⓘ</span></label><label v-if="!anonymous">Display name<input v-model="displayName" class="mt-1 w-full rounded-lg border p-2" /></label><button class="w-full rounded-xl bg-primary-600 p-3 text-white" @click="step = 4">Review</button></div>
  <div v-else-if="step === 4" class="space-y-4"><h3 class="text-lg font-bold">Review donation</h3><p>{{ type === 'point' ? points + ' points' : cash + ' THB' }} · {{ purpose || '—' }}</p><p v-if="error" class="text-sm text-red-600">{{ error }}</p><p v-for="(messages, field) in fieldErrors" :key="field" class="text-sm text-red-600">{{ field }}: {{ messages.join(', ') }}</p><button :disabled="loading" class="w-full rounded-xl bg-primary-600 p-3 text-white disabled:opacity-50" @click="submit">{{ loading ? 'Submitting…' : 'Submit donation' }}</button></div>
  <div v-else class="space-y-4 text-center"><h3 class="text-xl font-bold text-emerald-600">Donation submitted</h3><p>Donation ID: {{ result?.id }}</p><button class="rounded-xl bg-primary-600 px-5 py-3 text-white" @click="close">Close</button></div>
</Dialog></template>
