<script setup lang="ts">
import CourseDonationModal from '~/components/donation/CourseDonationModal.vue'
import { usePublicCourses, type PublicCourse, type PublicSupportSummary } from '~/composables/usePublicCourses'
const route = useRoute(); const auth = useAuthStore(); const { detail, supportSummary } = usePublicCourses(); const course = ref<PublicCourse | null>(null); const summary = ref<PublicSupportSummary | null>(null); const notFound = ref(false); const showDonation = ref(false)
try { const [courseResponse, summaryResponse] = await Promise.all([detail(route.params.slug as string), supportSummary(route.params.slug as string)]); course.value = courseResponse.data; summary.value = summaryResponse.data } catch { notFound.value = true }
const openDonation = () => { if (!auth.user) return navigateTo(`/login?return=${encodeURIComponent(route.fullPath)}`); showDonation.value = true }
useHead(() => ({ title: course.value?.name || 'Support a Course', meta: course.value?.cover ? [{ property: 'og:image', content: course.value.cover }] : [] }))
</script>
<template><main class="min-h-screen bg-slate-50 px-4 py-8 dark:bg-slate-950"><div class="mx-auto max-w-5xl"><div v-if="notFound" class="rounded-2xl bg-white p-12 text-center dark:bg-slate-900"><h1 class="text-2xl font-bold">This course doesn't accept donations</h1><NuxtLink to="/courses" class="mt-6 inline-block text-primary-600">ค้นหารายวิชาอื่น</NuxtLink></div><template v-else-if="course"><nav class="mb-5 text-sm text-slate-500"><NuxtLink to="/courses">Courses</NuxtLink> / {{ course.name }}</nav><section class="overflow-hidden rounded-3xl bg-white shadow-sm dark:bg-slate-900"><img v-if="course.cover" :src="course.cover" :alt="course.name" class="h-64 w-full object-cover md:h-80"><div class="p-6 md:p-10"><p class="text-sm text-primary-600">{{ course.academy?.name }}</p><h1 class="mt-2 text-3xl font-black md:text-4xl">{{ course.name }}</h1><p class="mt-3 text-slate-500">About the teacher: {{ course.teacher_display_name || 'Teacher' }}</p><p class="mt-8 whitespace-pre-line leading-7 text-slate-700 dark:text-slate-300">{{ course.description }}</p><button v-if="course.donation_enabled" class="mt-8 rounded-xl bg-amber-500 px-6 py-3 font-bold text-white shadow-lg" @click="openDonation">สนับสนุนรายวิชานี้ / Support this course</button></div></section><section class="mt-6 grid gap-6 md:grid-cols-2"><div class="rounded-2xl bg-white p-6 dark:bg-slate-900"><h2 class="text-xl font-bold">Active campaigns</h2><div v-for="item in summary?.campaign_progress || []" :key="item.campaign_id" class="mt-5"><div class="flex justify-between text-sm"><span>{{ item.title }}</span><span>{{ item.spent_budget }} / {{ item.total_budget ?? '∞' }}</span></div><div class="mt-2 h-2 rounded-full bg-slate-200"><div class="h-2 rounded-full bg-primary-600" :style="{ width: `${item.total_budget ? Math.min(100, item.spent_budget / item.total_budget * 100) : 0}%` }" /></div></div></div><div class="rounded-2xl bg-white p-6 dark:bg-slate-900"><h2 class="text-xl font-bold">Recent supporters</h2><div v-for="(donor, index) in summary?.recent_donors || []" :key="index" class="mt-4 flex items-center gap-3"><div class="flex h-9 w-9 items-center justify-center rounded-full bg-primary-100 text-primary-700">{{ donor.display_name.charAt(0) }}</div><span>{{ donor.display_name }}</span></div><p class="mt-5 text-sm text-slate-500">💎 {{ summary?.total_donated_points || 0 }} points · 👥 {{ summary?.total_donors || 0 }} donors</p></div></section><CourseDonationModal v-if="course.donation_enabled" v-model:visible="showDonation" :course-id="course.id" :course-name="course.name" :course-owner-id="0" :balance="auth.user?.pp" /></template></div></main></template>
