<script setup lang="ts">
import CourseSupportCard from '~/components/discovery/CourseSupportCard.vue'
import { usePublicCourses, type PublicCourseListParams, type PublicCourseListResponse } from '~/composables/usePublicCourses'
const route = useRoute(); const router = useRouter(); const { list } = usePublicCourses()
const q = ref(String(route.query.q || '')); const sort = ref<PublicCourseListParams['sort']>((route.query.sort as any) || 'recent'); const academyId = ref<number | undefined>(route.query.academy_id ? Number(route.query.academy_id) : undefined); const active = ref(route.query.active_campaign === '1');
const params = computed<PublicCourseListParams>(() => ({ q: q.value || undefined, sort: sort.value, academy_id: academyId.value, active_campaign: active.value || undefined, page: route.query.page ? Number(route.query.page) : 1 }))
const { data, pending, error, refresh } = await useAsyncData<PublicCourseListResponse>('public-courses', () => list(params.value), { watch: [() => route.query] })
const updateQuery = (extra: Record<string, any> = {}) => router.replace({ query: Object.fromEntries(Object.entries({ ...route.query, ...extra }).filter(([, v]) => v !== undefined && v !== '' && v !== false)) })
let timer: ReturnType<typeof setTimeout>; watch(q, value => { clearTimeout(timer); timer = setTimeout(() => updateQuery({ q: value || undefined, page: undefined }), 300) }); watch([sort, academyId, active], () => updateQuery({ sort: sort.value, academy_id: academyId.value, active_campaign: active.value ? '1' : undefined, page: undefined }))
watch(() => route.query, () => refresh())
useHead({ title: 'รายวิชาที่รับการสนับสนุน / Support a Course', meta: [{ name: 'description', content: 'ค้นหาและสนับสนุนรายวิชาที่คุณสนใจ' }] })
</script>
<template><main class="min-h-screen bg-slate-50 px-4 py-10 dark:bg-slate-950"><div class="mx-auto max-w-7xl"><section class="rounded-3xl bg-gradient-to-br from-primary-700 to-indigo-700 px-6 py-12 text-white shadow-xl md:px-12"><p class="mb-3 text-sm font-semibold uppercase tracking-widest text-primary-100">Nuxnan Discovery</p><h1 class="text-3xl font-black md:text-5xl">สนับสนุนรายวิชาที่คุณรัก</h1><p class="mt-3 max-w-2xl text-primary-100">ค้นพบรายวิชาและช่วยให้ผู้เรียนเข้าถึงโอกาสทางการศึกษา</p><input v-model="q" class="mt-8 w-full max-w-2xl rounded-2xl border-0 px-5 py-4 text-slate-900 shadow-lg outline-none" placeholder="ค้นหารายวิชา... / Search courses" /></section><div class="my-8 flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><select v-model="sort" class="rounded-xl border-slate-200 bg-transparent px-3 py-2 dark:border-slate-700"><option value="recent">ล่าสุด / Recent</option><option value="most_supported">ได้รับการสนับสนุนสูงสุด</option><option value="most_active">แคมเปญมากที่สุด</option></select><input v-model.number="academyId" type="number" class="w-36 rounded-xl border px-3 py-2" placeholder="Academy ID"><label class="flex items-center gap-2 text-sm"><input v-model="active" type="checkbox" class="rounded"> แคมเปญที่กำลังดำเนินการ</label></div><div v-if="pending" class="py-16 text-center text-slate-500">Loading...</div><div v-else-if="error || !data?.data?.length" class="rounded-2xl bg-white py-16 text-center dark:bg-slate-900"><p class="text-lg font-bold">ไม่พบรายวิชา</p><p class="mt-2 text-sm text-slate-500">ลองเปลี่ยนคำค้นหาหรือตัวกรอง</p></div><div v-else class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><CourseSupportCard v-for="course in data.data" :key="course.id" :course="course" /></div><div v-if="data?.meta?.last_page && data.meta.last_page > 1" class="mt-8 flex justify-center gap-2"><button v-for="page in data.meta.last_page" :key="page" class="rounded-lg px-3 py-2" :class="page === Number(route.query.page || 1) ? 'bg-primary-600 text-white' : 'bg-white dark:bg-slate-800'" @click="updateQuery({ page })">{{ page }}</button></div></div></main></template>
