<script setup lang="ts">
import { Icon } from '@iconify/vue'
import type { CoursePointCampaign } from '~/composables/useCoursePoints'
const props = defineProps<{ visible: boolean; courseId: number | string }>(); const emit = defineEmits<{ 'update:visible': [boolean]; updated: [] }>()
const { ownerCampaigns, fetchOwnerCampaigns, pauseCampaign, endCampaign } = useCoursePoints(computed(() => props.courseId)); const swal = useSweetAlert(); const close = () => emit('update:visible', false); const campaigns = computed(() => ownerCampaigns.value.filter(c => c.campaign_type === 'manual_claim'))
watch(() => props.visible, v => { if (v) fetchOwnerCampaigns() })
const percent = (c: CoursePointCampaign) => c.max_claims ? Math.min(100, Math.round(c.total_claimed / c.max_claims * 100)) : 0
const action = async (c: CoursePointCampaign, type: 'pause' | 'end') => { if (type === 'end' && !await swal.confirm('แคมเปญนี้จะจบถาวร', 'จบแคมเปญ?', { confirmText: 'จบแคมเปญ', cancelText: 'ยกเลิก', icon: 'warning', isDanger: true })) return; if (type === 'pause') await pauseCampaign(c.id); else await endCampaign(c.id); await fetchOwnerCampaigns(); emit('updated') }
</script>
<template><Transition name="modal-fade"><div v-if="visible" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm" @click.self="close"><Transition name="modal-slide" appear><div class="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-800"><div class="flex items-center justify-between"><h2 class="text-xl font-bold text-gray-900 dark:text-white">จัดการแคมเปญ</h2><button class="text-2xl text-gray-400" @click="close">×</button></div><div v-if="campaigns.length" class="mt-5 space-y-3"><article v-for="campaign in campaigns" :key="campaign.id" class="rounded-2xl border border-gray-200 p-4 dark:border-gray-700"><div class="flex justify-between gap-2"><h3 class="font-bold text-gray-900 dark:text-white">{{ campaign.title }}</h3><span class="rounded-full bg-vikinger-purple/10 px-2 py-1 text-xs text-vikinger-purple">{{ campaign.status }}</span></div><p class="mt-2 text-sm text-gray-500">{{ campaign.points_per_claim.toLocaleString() }} แต้มต่อการรับ · {{ campaign.total_claimed }}{{ campaign.max_claims ? `/${campaign.max_claims}` : '' }} ผู้รับ</p><div v-if="campaign.max_claims" class="mt-3 h-2 rounded-full bg-gray-100 dark:bg-gray-700"><div class="h-2 rounded-full bg-gradient-to-r from-violet-500 to-pink-500" :style="{ width: `${percent(campaign)}%` }" /></div><div v-if="['active'].includes(campaign.status)" class="mt-4 flex gap-2"><button class="rounded-xl border px-3 py-2 text-sm" @click="action(campaign, 'pause')">พัก</button><button class="rounded-xl bg-red-500 px-3 py-2 text-sm text-white" @click="action(campaign, 'end')">จบ</button></div></article></div><div v-else class="py-12 text-center text-gray-500"><Icon icon="mdi:party-popper" class="mx-auto h-14 w-14 text-amber-400" /><p class="mt-3">ยังไม่มีแคมเปญ ลองสร้างสักอัน!</p></div></div></Transition></div></Transition></template>
<style scoped>.modal-fade-enter-active,.modal-fade-leave-active{transition:opacity .2s}.modal-fade-enter-from,.modal-fade-leave-to{opacity:0}.modal-slide-enter-active,.modal-slide-leave-active{transition:transform .25s cubic-bezier(.4,0,.2,1)}.modal-slide-enter-from,.modal-slide-leave-to{transform:translateY(1rem) scale(.95)}</style>
