<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
const props = defineProps<{ visible: boolean; courseId: number; campaignId: number; campaignTitle: string; pointsPerClaim: number }>()
const emit = defineEmits<{ 'update:visible': [boolean]; claimed: [any] }>()
const { viewCampaign, claimCampaign } = useCoursePoints(computed(() => props.courseId))
const sweetAlert = useSweetAlert(); const donor = ref<any>(null); const donation = ref<any>(null); const seconds = ref(10); const points = ref(0); const loading = ref(false); const success = ref(false); let timer: ReturnType<typeof setInterval> | undefined
const clear = () => { if (timer) clearInterval(timer); timer = undefined }
const close = (value = false) => { clear(); emit('update:visible', value) }
const start = async () => { clear(); loading.value = true; success.value = false; points.value = 0; seconds.value = 10; try { const result: any = await viewCampaign(props.campaignId); donor.value = result.donor; donation.value = result.donation; seconds.value = result.view_duration_seconds || 10; const total = seconds.value * 10; let tick = 0; timer = setInterval(async () => { tick++; points.value = Math.round(props.pointsPerClaim * Math.min(1, tick / total)); seconds.value = Math.max(0, seconds.value - 0.1); if (tick >= total) { clear(); seconds.value = 0; const claim: any = await claimCampaign(props.campaignId, { viewed_donor_id: donor.value?.id, viewed_donation_id: donation.value?.id }); if (claim?.success) { success.value = true; emit('claimed', claim); setTimeout(() => close(false), 2000) } } }, 100) } finally { loading.value = false } }
const dismiss = async () => { if (seconds.value > 0 && !success.value) { if (await sweetAlert.confirm('แน่ใจไหม? ยังไม่ครบ 10 วินาที จะไม่ได้รับแต้ม')) close(false); } else close(false) }
watch(() => props.visible, value => { if (value) start(); else clear() }); onUnmounted(clear)
</script>
<template>
  <Transition name="modal-fade"><div v-if="visible" class="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4 backdrop-blur-md" @click.self="dismiss"><Transition name="modal-slide"><div class="relative w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-800"><button class="absolute right-4 top-4 text-2xl text-gray-400" @click="dismiss">×</button><h2 class="mb-5 pr-8 text-xl font-bold text-gray-900 dark:text-white">{{ campaignTitle }}</h2><div class="grid gap-5 md:grid-cols-2"><div class="rounded-2xl bg-violet-50 p-5 text-center dark:bg-violet-950/30"><template v-if="donor"><img :src="donor.avatar" class="mx-auto h-24 w-24 rounded-full object-cover" /><h3 class="mt-3 font-bold text-gray-900 dark:text-white">{{ donor.name }}</h3><p class="text-sm text-gray-500">@{{ donor.username }}</p><p v-if="donor.profile?.bio" class="mt-2 text-sm text-gray-600 dark:text-gray-300">{{ donor.profile.bio }}</p><p class="mt-3 text-sm font-semibold text-violet-600">บริจาค {{ donation?.points_amount }} แต้ม</p><p v-if="donation?.purpose" class="mt-1 text-xs text-gray-500">{{ donation.purpose }}</p><p class="mt-2 text-xs text-gray-500">รหัสผู้สนับสนุน: {{ donor.personal_code }}</p></template><template v-else><div class="py-12 text-5xl">🎁</div><h3 class="font-bold text-gray-900 dark:text-white">แต้มจากรายได้โฆษณา</h3></template></div><div class="flex flex-col items-center justify-center"><div class="relative flex h-40 w-40 items-center justify-center rounded-full border-[10px] border-violet-200 text-5xl font-black text-violet-600 dark:border-violet-900"><span v-if="success">🎉</span><span v-else>{{ Math.ceil(seconds) }}</span></div><p class="mt-5 text-3xl font-black text-violet-600">+{{ points.toLocaleString() }} แต้ม</p><p class="mt-2 text-sm text-gray-500">{{ success ? 'รับแต้มสำเร็จ!' : 'กรุณาดูให้ครบ 10 วินาที' }}</p></div></div></div></Transition></div></Transition>
</template>
<style scoped>.modal-fade-enter-active,.modal-fade-leave-active{transition:opacity .3s}.modal-fade-enter-from,.modal-fade-leave-to{opacity:0}.modal-slide-enter-active,.modal-slide-leave-active{transition:all .3s cubic-bezier(.4,0,.2,1)}.modal-slide-enter-from,.modal-slide-leave-to{opacity:0;transform:translateY(1rem) scale(.95)}</style>
