<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'

const props = defineProps<{ visible: boolean; courseId: number; campaignId: number; campaignTitle: string; pointsPerClaim: number }>()
const emit = defineEmits<{ 'update:visible': [boolean]; claimed: [any] }>()
const { viewCampaign, claimCampaign } = useCoursePoints(computed(() => props.courseId))
const sweetAlert = useSweetAlert()
const { start: startAd, heartbeat, complete } = useAdDelivery()
const mode = ref<'donor' | 'ad' | 'empty'>('donor'); const donor = ref<any>(null); const donation = ref<any>(null); const ad = ref<any>(null); const courseAvatar = ref<string | null>(null); const courseTitle = ref(''); const seconds = ref(10); const points = ref(0); const success = ref(false); const adReward = ref(0); const token = ref(''); const deliveryId = ref(0)
let timer: ReturnType<typeof setInterval> | undefined; let heartbeatTimer: ReturnType<typeof setInterval> | undefined
const clear = () => { if (timer) clearInterval(timer); if (heartbeatTimer) clearInterval(heartbeatTimer); timer = undefined; heartbeatTimer = undefined }
const close = () => { clear(); emit('update:visible', false) }
const finish = async () => { clear(); seconds.value = 0; if (mode.value === 'ad') { try { const result = await complete(deliveryId.value, token.value); adReward.value = result.valid ? (result.reward?.splits?.student || 0) : 0 } catch { adReward.value = 0 } } const claim = await claimCampaign(props.campaignId, mode.value === 'ad' ? { viewed_ad_id: ad.value?.id } : { viewed_donor_id: donor.value?.id, viewed_donation_id: donation.value?.id }); if (claim?.success) { success.value = true; emit('claimed', claim); setTimeout(close, 2000) } }
const start = async () => { clear(); success.value = false; points.value = 0; adReward.value = 0; const result: any = await viewCampaign(props.campaignId); mode.value = result.mode || (result.donor ? 'donor' : 'empty'); donor.value = result.donor; donation.value = result.donation; ad.value = result.ad; courseAvatar.value = result.course_avatar; courseTitle.value = result.course_title || ''; seconds.value = result.view_duration_seconds || 10; if (mode.value === 'ad' && ad.value) { const delivery = await startAd(ad.value.id); token.value = delivery.token; deliveryId.value = delivery.deliveryId; seconds.value = delivery.requiredDuration } const total = seconds.value * 10; let tick = 0; timer = setInterval(() => { tick++; points.value = Math.round(props.pointsPerClaim * Math.min(1, tick / total)); seconds.value = Math.max(0, seconds.value - 0.1); if (tick >= total) finish() }, 100); if (mode.value === 'ad') heartbeatTimer = setInterval(() => heartbeat(deliveryId.value, token.value, document.visibilityState === 'visible' ? 1 : 0).catch(() => {}), 5000) }
const dismiss = async () => { if (seconds.value > 0 && !success.value) { if (await sweetAlert.confirm(`ยังไม่ครบ ${Math.ceil(seconds.value)} วินาที จะไม่ได้รับแต้ม`)) close() } else close() }
watch(() => props.visible, value => value ? start() : clear()); onUnmounted(clear)
</script>
<template>
  <Transition name="modal-fade"><div v-if="visible" class="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4 backdrop-blur-md" @click.self="dismiss"><Transition name="modal-slide"><div class="relative w-full max-w-4xl rounded-3xl bg-white p-4 sm:p-6 shadow-2xl dark:bg-slate-800"><button class="absolute right-4 top-4 z-10 text-2xl text-gray-400" @click="dismiss">×</button><h2 class="mb-5 pr-8 text-xl font-bold text-gray-900 dark:text-white">{{ campaignTitle }}</h2><div v-if="mode === 'ad'" class="grid gap-5 md:grid-cols-2"><div class="flex min-h-64 items-center justify-center overflow-hidden rounded-2xl bg-black"><video v-if="['mp4','webm','ogg'].includes((ad?.media_image?.split('.').pop() || '').toLowerCase())" :src="ad?.media_image" class="h-full w-full object-contain" autoplay loop muted playsinline /><img v-else :src="ad?.media_image" class="h-full w-full object-contain" alt="Ad content" /></div><div class="flex flex-col items-center justify-center text-center"><p class="text-sm text-gray-500">{{ ad?.advertiser?.name }}</p><h3 class="mt-2 text-xl font-bold">{{ ad?.title }}</h3><p class="mt-2 text-sm text-gray-500">{{ ad?.description }}</p><div class="mt-6 text-5xl font-black text-violet-600">{{ success ? '🎉' : Math.ceil(seconds) }}</div><p class="mt-4 text-3xl font-black text-violet-600">+{{ points.toLocaleString() }} แต้ม</p><p v-if="adReward" class="mt-2 text-sm text-emerald-600">ได้จากโฆษณา +{{ adReward }}</p></div></div><div v-else class="grid gap-5 md:grid-cols-2"><div class="rounded-2xl bg-violet-50 p-5 text-center dark:bg-violet-950/30"><template v-if="mode === 'donor' && donor"><img :src="donor.avatar" class="mx-auto h-24 w-24 rounded-full object-cover" /><h3 class="mt-3 font-bold">{{ donor.name }}</h3><p class="text-sm text-gray-500">@{{ donor.username }}</p><p class="mt-3 text-sm font-semibold text-violet-600">บริจาค {{ donation?.points_amount }} แต้ม</p></template><template v-else><img v-if="courseAvatar" :src="courseAvatar" class="mx-auto h-24 w-24 rounded-full object-cover" /><div v-else class="py-8 text-5xl">🎓</div><h3 class="font-bold">{{ courseTitle }}</h3><p class="mt-4 font-semibold">ขอบคุณที่ร่วมสนับสนุนรายวิชานี้</p></template></div><div class="flex flex-col items-center justify-center"><div class="text-5xl font-black text-violet-600">{{ success ? '🎉' : Math.ceil(seconds) }}</div><p class="mt-5 text-3xl font-black text-violet-600">+{{ points.toLocaleString() }} แต้ม</p></div></div></div></Transition></div></Transition>
</template>
<style scoped>.modal-fade-enter-active,.modal-fade-leave-active{transition:opacity .3s}.modal-fade-enter-from,.modal-fade-leave-to{opacity:0}.modal-slide-enter-active,.modal-slide-leave-active{transition:all .3s}.modal-slide-enter-from,.modal-slide-leave-to{opacity:0;transform:translateY(1rem) scale(.95)}</style>
