<script setup lang="ts">
import { useCoursePointWithdrawals, type CoursePointWithdrawal } from '~/composables/useCoursePointWithdrawals'
const props = defineProps<{ visible: boolean; courseId: number | string }>(); const emit = defineEmits<{ 'update:visible': [boolean]; updated: [] }>(); const tab = ref<'withdraw' | 'history'>('withdraw'); const amount = ref<number | null>(null); const purpose = ref(''); const rows = ref<CoursePointWithdrawal[]>([]); const meta = ref<any>({}); const loading = ref(false); const error = ref(''); const swal = useSweetAlert(); const { createRequest, fetchCourseHistory, cancel } = useCoursePointWithdrawals(); const close = () => emit('update:visible', false)
const load = async (page = 1) => { const r = await fetchCourseHistory(Number(props.courseId), { page, per_page: 5 }); rows.value = r.data || []; meta.value = r.meta || {} }
watch(() => [props.visible, tab.value], ([visible, current]) => { if (visible && current === 'history') load() })
const submit = async () => { error.value = ''; if (!amount.value || amount.value < 24000) { error.value = 'ขั้นต่ำ 24,000 แต้ม'; return }; loading.value = true; try { await createRequest(Number(props.courseId), { amount: amount.value, purpose: purpose.value || undefined }); swal.toast('ส่งคำขอถอนแต้มสำเร็จ'); amount.value = null; purpose.value = ''; emit('updated'); tab.value = 'history'; await load() } catch (e: any) { error.value = e.data?.message || 'ไม่สามารถส่งคำขอได้' } finally { loading.value = false } }
const statusLabel = (s: string) => ({ pending: 'รอดำเนินการ', reviewing: 'กำลังตรวจสอบ', approved: 'อนุมัติแล้ว', paid: 'โอนแล้ว', rejected: 'ปฏิเสธ', cancelled: 'ยกเลิก' }[s] || s); const cancelRow = async (row: CoursePointWithdrawal) => { if (await swal.confirm('แต้มจะถูกคืนเข้ากองทุนรายวิชาทันที', 'ยกเลิกคำขอถอน?', { confirmText: 'ยกเลิกคำขอ', cancelText: 'ไม่ใช่', icon: 'warning', isDanger: true })) { await cancel(row.id); await load(meta.value.current_page || 1); emit('updated') } }
</script>
<template><Transition name="modal-fade"><div v-if="visible" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm" @click.self="close"><Transition name="modal-slide" appear><div class="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-800"><div class="flex items-center justify-between"><h2 class="text-xl font-bold text-gray-900 dark:text-white">ถอนแต้ม</h2><button class="text-2xl text-gray-400" @click="close">×</button></div><div class="mt-5 flex rounded-2xl bg-gray-100 p-1 dark:bg-slate-700"><button class="min-h-[44px] sm:min-h-0 flex-1 rounded-xl p-2 text-sm" :class="tab === 'withdraw' ? 'bg-white shadow dark:bg-slate-600' : ''" @click="tab = 'withdraw'">ถอน</button><button class="min-h-[44px] sm:min-h-0 flex-1 rounded-xl p-2 text-sm" :class="tab === 'history' ? 'bg-white shadow dark:bg-slate-600' : ''" @click="tab = 'history'">ประวัติ</button></div><form v-if="tab === 'withdraw'" class="mt-5 space-y-4" @submit.prevent="submit"><input v-model.number="amount" type="number" min="24000" placeholder="จำนวนแต้ม" class="w-full rounded-3xl border p-3 dark:border-gray-600 dark:bg-slate-700" /><textarea v-model="purpose" rows="3" placeholder="เหตุผลการถอน" class="w-full rounded-3xl border p-3 dark:border-gray-600 dark:bg-slate-700" /><p v-if="error" class="text-sm text-red-600">{{ error }}</p><button :disabled="loading" class="w-full rounded-3xl bg-gradient-to-r from-violet-500 via-pink-500 to-amber-400 p-3 font-bold text-white disabled:opacity-50">{{ loading ? 'กำลังส่ง...' : 'ส่งคำขอถอน' }}</button></form><div v-else class="mt-5 space-y-3"><div v-for="row in rows" :key="row.id" class="rounded-2xl border p-3 dark:border-gray-700"><div class="flex justify-between"><b>{{ row.amount.toLocaleString() }} แต้ม</b><span class="text-sm text-vikinger-purple">{{ statusLabel(row.status) }}</span></div><p class="mt-1 text-xs text-gray-500">{{ row.purpose || '—' }}</p><button v-if="['pending','reviewing'].includes(row.status)" class="mt-2 text-sm text-red-500" @click="cancelRow(row)">ยกเลิก</button></div><p v-if="!rows.length" class="py-8 text-center text-sm text-gray-500">ยังไม่มีประวัติการถอน</p><div v-if="rows.length" class="flex justify-between text-sm"><button :disabled="!meta.current_page || meta.current_page <= 1" @click="load(meta.current_page - 1)">ก่อนหน้า</button><span>{{ meta.current_page || 1 }}</span><button :disabled="!meta.last_page || meta.current_page >= meta.last_page" @click="load(meta.current_page + 1)">ถัดไป</button></div></div></div></Transition></div></Transition></template>
<style scoped>.modal-fade-enter-active,.modal-fade-leave-active{transition:opacity .2s}.modal-fade-enter-from,.modal-fade-leave-to{opacity:0}.modal-slide-enter-active,.modal-slide-leave-active{transition:transform .25s cubic-bezier(.4,0,.2,1)}.modal-slide-enter-from,.modal-slide-leave-to{transform:translateY(1rem) scale(.95)}</style>
