<script setup lang="ts">
definePageMeta({ layout: 'course', middleware: ['auth'] })
const route = useRoute(); const id = computed(() => Number(route.params.id)); const store = useCourseStore(); const swal = useSweetAlert()
onBeforeMount(async () => { if (!store.currentCourse || store.currentCourse.id !== id.value) await store.fetchCourse(id.value); if (!store.isCourseAdmin) return navigateTo(`/courses/${id.value}`) })
const { account, fetchAccount, ownerCampaigns, fetchOwnerCampaigns, createManualCampaign, pauseCampaign, endCampaign } = useCoursePoints(id)
const form = reactive({ title: '', description: '', points_per_claim: 100, max_claims: null as number | null, starts_at: '', ends_at: '' }); const limited = ref(false); const loading = ref(false)
const reserve = computed(() => limited.value && form.max_claims ? form.points_per_claim * form.max_claims : null); const insufficient = computed(() => !!reserve.value && reserve.value > (account.value?.available_balance || 0)); const manuals = computed(() => ownerCampaigns.value.filter(c => c.campaign_type === 'manual_claim'))
onMounted(() => Promise.all([fetchAccount(), fetchOwnerCampaigns()]))
const submit = async () => { if (!form.title || insufficient.value) return; loading.value = true; try { await createManualCampaign({ ...form, max_claims: limited.value ? form.max_claims : null }); await Promise.all([fetchAccount(), fetchOwnerCampaigns()]); form.title = ''; form.description = ''; swal.toast('สร้างแคมเปญสำเร็จ', 'success') } catch (e: any) { swal.error(e?.data?.message || 'สร้างแคมเปญไม่สำเร็จ') } finally { loading.value = false } }
const pause = async (c: any) => { await pauseCampaign(c.id); await fetchOwnerCampaigns() }; const end = async (c: any) => { if (await swal.confirm('ยืนยันการจบแคมเปญนี้?')) { await endCampaign(c.id); await Promise.all([fetchOwnerCampaigns(), fetchAccount()]) } }
</script>
<template><div class="mx-auto max-w-7xl space-y-6 p-6"><div class="flex items-center justify-between"><h1 class="text-2xl font-bold">จัดการแคมเปญแต้ม</h1><NuxtLink :to="`/courses/${id}/wallet/withdraw`" class="text-primary-600">ไปหน้าถอนแต้ม</NuxtLink></div><div class="grid gap-6 lg:grid-cols-2"><section class="rounded-2xl bg-white p-6 shadow dark:bg-slate-800"><h2 class="mb-4 text-lg font-semibold">สร้างแคมเปญแจกแต้ม</h2><p>ยอดแต้มที่ใช้ได้: {{ account?.available_balance?.toLocaleString() || 0 }}</p><div class="mt-4 space-y-4"><input v-model="form.title" required placeholder="ชื่อแคมเปญ *" class="w-full rounded-lg border p-3" /><textarea v-model="form.description" placeholder="รายละเอียด" class="w-full rounded-lg border p-3" /><input v-model.number="form.points_per_claim" required type="number" min="1" placeholder="แต้มต่อคน *" class="w-full rounded-lg border p-3" /><label><input v-model="limited" type="checkbox" /> จำกัดจำนวนผู้รับ</label><input v-if="limited" v-model.number="form.max_claims" type="number" min="1" placeholder="จำนวนผู้รับสูงสุด" class="w-full rounded-lg border p-3" /><div class="grid gap-4 sm:grid-cols-2"><input v-model="form.starts_at" type="datetime-local" class="rounded-lg border p-3" /><input v-model="form.ends_at" type="datetime-local" class="rounded-lg border p-3" /></div><p v-if="reserve" :class="insufficient ? 'text-red-600' : 'text-amber-600'">ต้องกันแต้ม {{ reserve.toLocaleString() }} แต้ม{{ insufficient ? ' — แต้มไม่เพียงพอ' : '' }}</p><button :disabled="loading || !form.title || insufficient" class="w-full rounded-lg bg-primary-600 p-3 text-white disabled:opacity-50" @click="submit">สร้างแคมเปญ</button></div></section><section class="overflow-x-auto rounded-2xl bg-white shadow dark:bg-slate-800"><h2 class="p-6 text-lg font-semibold">แคมเปญของฉัน</h2><table class="w-full text-left text-sm"><thead><tr><th class="p-4">ชื่อ</th><th class="p-4">แต้ม/คน</th><th class="p-4">ผู้รับ</th><th class="p-4">สถานะ</th><th class="p-4">ดำเนินการ</th></tr></thead><tbody><tr v-for="c in manuals" :key="c.id" class="border-t"><td class="p-4">{{ c.title }}</td><td class="p-4">{{ c.points_per_claim }}</td><td class="p-4">{{ c.total_claimed }}/{{ c.max_claims ?? '∞' }}</td><td class="p-4">{{ c.status }}</td><td class="p-4"><button v-if="c.status === 'active'" @click="pause(c)">พัก</button> <button v-if="['active','paused'].includes(c.status)" class="text-red-600" @click="end(c)">จบ</button></td></tr></tbody></table></section></div></div></template>
