<script setup lang="ts">
import { useCoursePointWithdrawals, type CoursePointWithdrawal } from '~/composables/useCoursePointWithdrawals'
import { useCoursePoints } from '~/composables/useCoursePoints'
definePageMeta({ layout: 'course', middleware: ['auth'] })
const route = useRoute(); const id = computed(() => Number(route.params.id)); const { createRequest, fetchCourseHistory, cancel } = useCoursePointWithdrawals(); const { account, fetchAccount } = useCoursePoints(id)
const rows = ref<CoursePointWithdrawal[]>([]); const meta = ref<any>({}); const amount = ref<number | null>(null); const purpose = ref(''); const errors = ref<Record<string, string[]>>({}); const message = ref(''); const loading = ref(false)
const load = async (page = 1) => { const r = await fetchCourseHistory(id.value, { page, per_page: 10 }); rows.value = r.data; meta.value = r.meta }
onMounted(async () => { await Promise.all([fetchAccount(), load()]) })
const submit = async () => { errors.value = {}; message.value = ''; if (!amount.value || amount.value < 24000) { errors.value.amount = ['ขั้นต่ำ 24,000 แต้ม']; return }; loading.value = true; try { await createRequest(id.value, { amount: amount.value, purpose: purpose.value || undefined }); message.value = 'ส่งคำขอถอนแต้มสำเร็จ'; amount.value = null; purpose.value = ''; await Promise.all([load(), fetchAccount()]) } catch (e: any) { if (e.status === 422) errors.value = e.data?.errors || {}; else if (e.status === 429) message.value = 'คำขอถูกจำกัดชั่วคราว กรุณาลองใหม่ภายหลัง'; else message.value = e.data?.message || 'ไม่สามารถส่งคำขอได้' } finally { loading.value = false } }
const canCancel = (r: CoursePointWithdrawal) => ['pending', 'reviewing'].includes(r.status)
const statusLabel = (s: string) => ({ pending: 'รอดำเนินการ', reviewing: 'กำลังตรวจสอบ', approved: 'อนุมัติแล้ว', paid: 'โอนแล้ว', rejected: 'ปฏิเสธ', cancelled: 'ยกเลิก' }[s] || s)
</script>
<template><div class="mx-auto max-w-7xl space-y-6 p-6"><div class="flex items-center justify-between"><h1 class="text-2xl font-bold">{{ $t('withdrawal.title') }}</h1><NuxtLink :to="`/courses/${id}/wallet`" class="text-primary-600">กระเป๋าแต้ม</NuxtLink></div><div v-if="message" class="rounded-xl bg-emerald-50 p-4 text-emerald-700">{{ message }}</div><div class="grid gap-6 lg:grid-cols-3"><section class="rounded-2xl bg-white p-6 shadow dark:bg-slate-800"><h2 class="mb-4 text-lg font-semibold">{{ $t('withdrawal.request') }}</h2><p class="mb-4 text-sm text-slate-500">ยอดใช้ได้: {{ account?.available_balance?.toLocaleString() || 0 }} แต้ม</p><label class="text-sm">{{ $t('withdrawal.amount') }}<input v-model.number="amount" type="number" min="24000" class="mt-1 w-full rounded-lg border p-3" /></label><p class="mt-1 text-xs text-slate-500">ขั้นต่ำ 24,000 แต้ม (= 20 บาท)</p><p v-if="errors.amount" class="text-sm text-red-600">{{ errors.amount[0] }}</p><label class="mt-4 block text-sm">{{ $t('withdrawal.purpose') }}<textarea v-model="purpose" maxlength="500" rows="4" class="mt-1 w-full rounded-lg border p-3" /></label><p v-if="errors.purpose" class="text-sm text-red-600">{{ errors.purpose[0] }}</p><button :disabled="loading" class="mt-5 w-full rounded-lg bg-primary-600 p-3 text-white disabled:opacity-50" @click="submit">{{ loading ? 'กำลังส่ง…' : 'ส่งคำขอ' }}</button></section><section class="overflow-hidden rounded-2xl bg-white shadow dark:bg-slate-800 lg:col-span-2"><div class="border-b p-6"><h2 class="text-lg font-semibold">ประวัติการถอน</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 dark:bg-slate-700"><tr><th class="p-4">วันที่</th><th class="p-4">จำนวน</th><th class="p-4">วัตถุประสงค์</th><th class="p-4">สถานะ</th><th class="p-4">ดำเนินการ</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id" class="border-t dark:border-slate-700"><td class="p-4">{{ new Date(r.requested_at).toLocaleDateString() }}</td><td class="p-4">{{ r.amount.toLocaleString() }}</td><td class="p-4">{{ r.purpose || '—' }}</td><td class="p-4"><span class="rounded-full bg-slate-100 px-2 py-1">{{ statusLabel(r.status) }}</span></td><td class="p-4"><button v-if="canCancel(r)" class="text-red-600" @click="cancel(r.id).then(() => load(meta.current_page || 1))">ยกเลิก</button></td></tr><tr v-if="!rows.length"><td colspan="5" class="p-8 text-center text-slate-500">ยังไม่มีรายการ</td></tr></tbody></table></div><div class="flex justify-between p-4"><button :disabled="!meta.current_page || meta.current_page <= 1" @click="load(meta.current_page - 1)">ก่อนหน้า</button><span>{{ meta.current_page || 1 }}</span><button :disabled="!meta.last_page || meta.current_page >= meta.last_page" @click="load(meta.current_page + 1)">ถัดไป</button></div></section></div></div></template>
